In [4]:
import cv2 as cv
import numpy as np
import mediapipe as mp
import matplotlib.pyplot as plt
import math
import imutils

url="https://file.io/a3Wzwecb1wd4"

import cv2
import urllib
import numpy as np

req = urllib.request.urlopen(url)
print(req.read)
arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
img = cv2.imdecode(arr, -1) # 'Load it as it is'
print(img)
cv2.imshow('lalala', img)
if cv2.waitKey() & 0xff == 27: quit()

<bound method HTTPResponse.read of <http.client.HTTPResponse object at 0x1120a3df0>>
[[[132 126 131]
  [135 129 134]
  [132 126 131]
  ...
  [130 124 159]
  [132 126 161]
  [130 124 159]]

 [[129 123 128]
  [136 130 135]
  [139 133 138]
  ...
  [130 124 159]
  [131 125 160]
  [129 123 158]]

 [[119 113 118]
  [127 121 126]
  [132 126 131]
  ...
  [132 126 161]
  [132 126 161]
  [133 127 162]]

 ...

 [[ 25  21  32]
  [ 30  26  37]
  [ 32  28  39]
  ...
  [ 50  42  49]
  [ 54  46  53]
  [ 53  45  52]]

 [[ 30  26  37]
  [ 27  23  34]
  [ 24  20  31]
  ...
  [ 44  36  43]
  [ 49  41  48]
  [ 55  47  54]]

 [[ 31  27  38]
  [ 27  23  34]
  [ 25  21  32]
  ...
  [ 40  32  39]
  [ 46  38  45]
  [ 52  44  51]]]


: 